export enum ActionTypes {
  SET_SOURCE_LANGUAGE = 'setSourceLanguage',
  SET_TARGET_LANGUAGE = 'setTargetLanguage',
  SET_SOURCE_TEXT = 'setSourceText',
  SET_TARGET_TEXT = 'setTargetText',
  SET_IS_FAVOURITE = 'setIsFavourite',
  SET_LANGUAGES = 'setLanguages',
  CLEAR_HISTORY = 'clearHistory',
  ADD_ITEM_TO_HISTORY = 'addItemToHistory',
  REMOVE_ITEM_FROM_HISTORY = 'removeItemFromHistory',
  UPDATE_ITEM_IN_HISTORY = 'updateItemInHistory',
  GET_HISTORY = 'getHistory',
  GET_FAVOURITES = 'getFavourites',
  EXCHANGE_LANGUAGES = 'exchangeLanguages',
}
